version: '3.8'
services:
  service1:
    build: ./service1
    ports:
      - "5000:5000"
    networks:
      - microservices_network

  service2:
    build: ./service2
    ports:
      - "5001:5001"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge